# Generated by Django 4.1.1 on 2022-10-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_remove_brand_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
