# Generated by Django 4.1.1 on 2022-10-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_category_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_offer',
        ),
    ]
