# Generated by Django 4.1.1 on 2022-10-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_offer_delete_brandoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category_name',
        ),
    ]
