# Generated by Django 4.1.1 on 2022-10-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_brandoffer_delete_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BrandOffer',
        ),
    ]
