# Generated by Django 4.1.1 on 2022-09-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_is_blocked_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_phone_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
