# Generated by Django 4.1.1 on 2022-09-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_is_phone_verfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_phone_verfied',
            new_name='is_phone_verified',
        ),
    ]
