# Generated by Django 4.1.1 on 2022-10-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
