# Generated by Django 4.1.1 on 2022-10-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_delete_productoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='BrandOffer',
        ),
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
    ]
